### ISSUE TITLE
Overlapping UI

### ISSUE THREAD

**Issue by Hotkeq** [InventivetalentDev/SkyblockBossTimerMod#1]
I really like this mod, Its just a shame that it overlaps my current ui. https://gyazo.com/0b0fe9362428ed6df60df69396ecbf44
Wonding if this will be customisable in future updates, as id much prefer a warning to appear in the middle of the screen saying 'Boss in 5m' for a few seconds instead of in the top right for 20m

**Comment by InventivetalentDev** [comment]
Sorry! Forgot to mention that in the readme. You can actually adjust the position in the Mod Options (provide by Forge). 
I might add more options for warnings etc. in the future, wasn't too sure about adding that though, since the SkyblockAddons thingy already has a large red text warning you when the boss spawns.

**Comment by Hotkeq** [comment]
Forge doesn't show any config for the mod. https://gyazo.com/d18401bbffd7c369365e2a83a19f0d9f
Is this a 1.12 feature?

**Comment by InventivetalentDev** [comment]
Oh right. Yeah, that's a 1.12 thing.  
I'm not really planning on adding an extra thing for 1.8.9, sorry.

**Comment by Hotkeq** [comment]
Not even a way to just remove the icon in the top right?

**Comment by InventivetalentDev** [comment]
Yeah, bit hard to add when the mod options don't work in that version ^^  

*sigh* I will try to look into adding the options separately for 1.8.9, no promises though!

**Comment by Hotkeq** [comment]
Really? I have other mods which have mod options like schematica

**Comment by Hotkeq** [comment]
Anyhow I appreciate your efforts and love the mod 😄

**Comment by InventivetalentDev** [comment]
> Really? I have other mods which have mod options like schematica

Hmm, Imma look into that!

**Comment by InventivetalentDev** [comment]
Pushed a 1.1.1 version for 1.8.9 which should have working mod options now :)

**Comment by Hotkeq** [comment]
Working perfect ty :)
